version: "3"

services:
  limit-request-redis:
    container_name: limit-request-redis
    image: redis:5
    command: redis-server --appendonly yes
    ports:
      - "6383:6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - limit-request
  
  limit-request-mysql:
    container_name: limit-request-mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - ./sql/limit-request.local.sql:/docker-entrypoint-initdb.d/limit-request.sql
      # - ./data/mysql:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    ports:
      - "3318:3306"
    networks:
      - limit-request
volumes:
  sql:
    driver: local
  redis_data:
    driver: local
networks:
  limit-request:
    driver: bridge
